apiVersion: v1
kind: Service
metadata:
  name: {{ include "basebackend-admin-api.fullname" . }}
  namespace: {{ .Release.Namespace | default "basebackend" }}
  labels:
    {{- include "basebackend-admin-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.monitoring.enabled }}
    prometheus.io/scrape: {{ .Values.monitoring.serviceMonitor.enabled | quote }}
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basebackend-admin-api.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "basebackend-admin-api.fullname" . }}-headless
  namespace: {{ .Release.Namespace | default "basebackend" }}
  labels:
    {{- include "basebackend-admin-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basebackend-admin-api.selectorLabels" . | nindent 4 }}
