spring:
  datasource:
    url: jdbc:mysql://1.117.67.222:3306/basebackend_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: basebackend_admin
    password: 5iA7pGWQJnACwXw3

logging:
  level:
    com.basebackend.generator: DEBUG
