apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: basebackend

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: admin-api
  app.kubernetes.io/part-of: basebackend
  app.kubernetes.io/managed-by: kustomize

images:
  - name: docker.io/YOUR_USERNAME/basebackend-admin-api
    newName: docker.io/YOUR_USERNAME/basebackend-admin-api
    newTag: latest
